In [1]:
import pandas as pd
data = pd.read_csv('advertising.csv')
data.head(5)

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 00:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 01:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 02:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 03:36:18,0

In [7]:
data['Clicked on Ad']

0      0
1      0
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: Clicked on Ad, Length: 1000, dtype: int64

In [2]:
#checking how many null values 
data.isnull().sum()

Daily Time Spent on Site    0
Age                         0
Area Income                 0
Daily Internet Usage        0
Ad Topic Line               0
City                        0
Male                        0
Country                     0
Timestamp                   0
Clicked on Ad               0
dtype: int64

In [3]:
#features of dataset
data.columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage', 'Ad Topic Line', 'City', 'Male', 'Country',
       'Timestamp', 'Clicked on Ad'],
      dtype='object')

In [4]:
x=data.iloc[:,0:7]
x=x.drop(['Ad Topic Line','City'],axis=1)
x

     Daily Time Spent on Site  Age  Area Income  Daily Internet Usage  Male
0                       68.95   35     61833.90                256.09     0
1                       80.23   31     68441.85                193.77     1
2                       69.47   26     59785.94                236.50     0
3                       74.15   29     54806.18                245.89     1
4                       68.37   35     73889.99                225.58     0
..                        ...  ...          ...                   ...   ...
995                     72.97   30     71384.57                208.58     1
996                     51.30   45     67782.17                134.42     1
997                     51.63   51     42415.72                120.37     1
998                     55.55   19     41920.79                187.95     0
999                     45.01   26     29875.80                178.35     0

[1000 rows x 5 columns]

In [5]:
y=data.iloc[:,9]
y

0      0
1      0
2      0
3      0
4      0
      ..
995    1
996    1
997    1
998    0
999    1
Name: Clicked on Ad, Length: 1000, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(700, 5)
(700,)
(300, 5)
(300,)

In [9]:
from sklearn.linear_model import LogisticRegression
Lr=LogisticRegression(C=0.01,random_state=0)
Lr.fit(x_train,y_train)
y_pred=Lr.predict(x_test)
print(y_pred)

[0 0 0 1 1 0 0 1 0 1 1 0 0 0 1 1 0 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1
 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 1 1 0 0 0
 0 1 1 1 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0
 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 0 0
 1 0 0 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 1 0 1 1 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0
 0 1 0 1 0 1 1 1 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0
 0 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1
 1 0 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 1
 1 0 0 0]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

In [10]:
y_pred_proba=Lr.predict_proba(x_test)
print(y_pred_proba)

[[0.94978968 0.05021032]
 [0.8994069  0.1005931 ]
 [0.69359956 0.30640044]
 [0.35049399 0.64950601]
 [0.03476647 0.96523353]
 [0.77835822 0.22164178]
 [0.97617657 0.02382343]
 [0.02075395 0.97924605]
 [0.79999193 0.20000807]
 [0.00725797 0.99274203]
 [0.44131897 0.55868103]
 [0.5821016  0.4178984 ]
 [0.96526723 0.03473277]
 [0.69478151 0.30521849]
 [0.00259367 0.99740633]
 [0.00634977 0.99365023]
 [0.9717238  0.0282762 ]
 [0.00465741 0.99534259]
 [0.98112465 0.01887535]
 [0.01057871 0.98942129]
 [0.05778635 0.94221365]
 [0.87601019 0.12398981]
 [0.34845123 0.65154877]
 [0.46538551 0.53461449]
 [0.11845054 0.88154946]
 [0.93429692 0.06570308]
 [0.95626029 0.04373971]
 [0.04643636 0.95356364]
 [0.75306086 0.24693914]
 [0.98196412 0.01803588]
 [0.9567504  0.0432496 ]
 [0.1604241  0.8395759 ]
 [0.06395605 0.93604395]
 [0.00110026 0.99889974]
 [0.97954706 0.02045294]
 [0.30665773 0.69334227]
 [0.06305196 0.93694804]
 [0.92721422 0.07278578]
 [0.25622832 0.74377168]
 [0.90935596 0.09064404]
 [0.67584979 0.32415021]
 [0.45721278 0.54278722]
 [0.53807624 0.46192376]
 [0.06511369 0.93488631]
 [0.92247548 0.07752452]
 [0.00438451 0.99561549]
 [0.96965039 0.03034961]
 [0.95658288 0.04341712]
 [0.98075922 0.01924078]
 [0.98236038 0.01763962]
 [0.09642636 0.90357364]
 [0.14135071 0.85864929]
 [0.96513701 0.03486299]
 [0.10952242 0.89047758]
 [0.85110233 0.14889767]
 [0.10091688 0.89908312]
 [0.8620491  0.1379509 ]
 [0.7874832  0.2125168 ]
 [0.98504767 0.01495233]
 [0.01817675 0.98182325]
 [0.00190224 0.99809776]
 [0.00347545 0.99652455]
 [0.05667061 0.94332939]
 [0.9505472  0.0494528 ]
 [0.00160197 0.99839803]
 [0.94696082 0.05303918]
 [0.94732525 0.05267475]
 [0.68796095 0.31203905]
 [0.95989534 0.04010466]
 [0.0107801  0.9892199 ]
 [0.47648389 0.52351611]
 [0.72067317 0.27932683]
 [0.94167858 0.05832142]
 [0.96799869 0.03200131]
 [0.54550949 0.45449051]
 [0.22118056 0.77881944]
 [0.02289262 0.97710738]
 [0.00174732 0.99825268]
 [0.88117718 0.11882282]
 [0.04027667 0.95972333]
 [0.95651046 0.04348954]
 [0.00566025 0.99433975]
 [0.89714031 0.10285969]
 [0.68638028 0.31361972]
 [0.96802148 0.03197852]
 [0.90177638 0.09822362]
 [0.23868985 0.76131015]
 [0.91472609 0.08527391]
 [0.17637167 0.82362833]
 [0.96000851 0.03999149]
 [0.82828747 0.17171253]
 [0.00491228 0.99508772]
 [0.94168903 0.05831097]
 [0.96796214 0.03203786]
 [0.04110339 0.95889661]
 [0.8064175  0.1935825 ]
 [0.95109794 0.04890206]
 [0.891881   0.108119  ]
 [0.9647232  0.0352768 ]
 [0.9698863  0.0301137 ]
 [0.947178   0.052822  ]
 [0.026131   0.973869  ]
 [0.98624803 0.01375197]
 [0.62443078 0.37556922]
 [0.72690214 0.27309786]
 [0.73035952 0.26964048]
 [0.56690842 0.43309158]
 [0.88106618 0.11893382]
 [0.30778773 0.69221227]
 [0.07351315 0.92648685]
 [0.97433972 0.02566028]
 [0.32100578 0.67899422]
 [0.97192705 0.02807295]
 [0.94533769 0.05466231]
 [0.18737223 0.81262777]
 [0.46861026 0.53138974]
 [0.01323331 0.98676669]
 [0.61913443 0.38086557]
 [0.84035712 0.15964288]
 [0.22472597 0.77527403]
 [0.89814708 0.10185292]
 [0.00340356 0.99659644]
 [0.00402449 0.99597551]
 [0.69547525 0.30452475]
 [0.00627164 0.99372836]
 [0.01305758 0.98694242]
 [0.98080117 0.01919883]
 [0.94111208 0.05888792]
 [0.01307987 0.98692013]
 [0.01559194 0.98440806]
 [0.98784995 0.01215005]
 [0.81914297 0.18085703]
 [0.83502101 0.16497899]
 [0.8668777  0.1331223 ]
 [0.90863243 0.09136757]
 [0.02921532 0.97078468]
 [0.95234656 0.04765344]
 [0.95388315 0.04611685]
 [0.42833421 0.57166579]
 [0.52963228 0.47036772]
 [0.32004493 0.67995507]
 [0.32154272 0.67845728]
 [0.76919736 0.23080264]
 [0.92424105 0.07575895]
 [0.97230155 0.02769845]
 [0.19971678 0.80028322]
 [0.94499935 0.05500065]
 [0.91428774 0.08571226]
 [0.41673827 0.58326173]
 [0.95721631 0.04278369]
 [0.96243096 0.03756904]
 [0.00834865 0.99165135]
 [0.71548936 0.28451064]
 [0.5576158  0.4423842 ]
 [0.00461139 0.99538861]
 [0.94821461 0.05178539]
 [0.90230366 0.09769634]
 [0.21437788 0.78562212]
 [0.61937052 0.38062948]
 [0.79279024 0.20720976]
 [0.98930514 0.01069486]
 [0.91414325 0.08585675]
 [0.0086861  0.9913139 ]
 [0.00946202 0.99053798]
 [0.02535668 0.97464332]
 [0.00275563 0.99724437]
 [0.00899463 0.99100537]
 [0.9854503  0.0145497 ]
 [0.06505703 0.93494297]
 [0.03194325 0.96805675]
 [0.97841289 0.02158711]
 [0.98337901 0.01662099]
 [0.23105483 0.76894517]
 [0.97627224 0.02372776]
 [0.00921489 0.99078511]
 [0.96306878 0.03693122]
 [0.98279465 0.01720535]
 [0.94199051 0.05800949]
 [0.04509256 0.95490744]
 [0.14135011 0.85864989]
 [0.95302142 0.04697858]
 [0.92617628 0.07382372]
 [0.92136397 0.07863603]
 [0.00608285 0.99391715]
 [0.63900818 0.36099182]
 [0.96752021 0.03247979]
 [0.11396487 0.88603513]
 [0.97263439 0.02736561]
 [0.11377616 0.88622384]
 [0.96241364 0.03758636]
 [0.22460254 0.77539746]
 [0.12757922 0.87242078]
 [0.01382184 0.98617816]
 [0.01859064 0.98140936]
 [0.7677928  0.2322072 ]
 [0.40653685 0.59346315]
 [0.01273799 0.98726201]
 [0.94101652 0.05898348]
 [0.87800007 0.12199993]
 [0.87680913 0.12319087]
 [0.05899468 0.94100532]
 [0.9822591  0.0177409 ]
 [0.96525616 0.03474384]
 [0.98757718 0.01242282]
 [0.91879269 0.08120731]
 [0.97453627 0.02546373]
 [0.6563952  0.3436048 ]
 [0.92312384 0.07687616]
 [0.45128463 0.54871537]
 [0.78210494 0.21789506]
 [0.97916192 0.02083808]
 [0.96773212 0.03226788]
 [0.96612805 0.03387195]
 [0.9205127  0.0794873 ]
 [0.00348273 0.99651727]
 [0.09723856 0.90276144]
 [0.03451516 0.96548484]
 [0.04319128 0.95680872]
 [0.47631118 0.52368882]
 [0.04831766 0.95168234]
 [0.10864814 0.89135186]
 [0.96399424 0.03600576]
 [0.6577881  0.3422119 ]
 [0.0066436  0.9933564 ]
 [0.77825097 0.22174903]
 [0.8583683  0.1416317 ]
 [0.85910776 0.14089224]
 [0.3777697  0.6222303 ]
 [0.0205564  0.9794436 ]
 [0.82393134 0.17606866]
 [0.95964598 0.04035402]
 [0.96464503 0.03535497]
 [0.92565918 0.07434082]
 [0.00208383 0.99791617]
 [0.98632033 0.01367967]
 [0.16748951 0.83251049]
 [0.89369114 0.10630886]
 [0.97325388 0.02674612]
 [0.00226677 0.99773323]
 [0.01041281 0.98958719]
 [0.55971984 0.44028016]
 [0.99061689 0.00938311]
 [0.95577527 0.04422473]
 [0.13604135 0.86395865]
 [0.08605474 0.91394526]
 [0.89087204 0.10912796]
 [0.05222206 0.94777794]
 [0.04286529 0.95713471]
 [0.56726191 0.43273809]
 [0.00121649 0.99878351]
 [0.0454863  0.9545137 ]
 [0.94074699 0.05925301]
 [0.00156468 0.99843532]
 [0.00583424 0.99416576]
 [0.01243058 0.98756942]
 [0.00358824 0.99641176]
 [0.16939333 0.83060667]
 [0.05482917 0.94517083]
 [0.0784888  0.9215112 ]
 [0.05402643 0.94597357]
 [0.97249468 0.02750532]
 [0.0061924  0.9938076 ]
 [0.58645787 0.41354213]
 [0.00867111 0.99132889]
 [0.93457288 0.06542712]
 [0.93448198 0.06551802]
 [0.42558468 0.57441532]
 [0.90644179 0.09355821]
 [0.97743235 0.02256765]
 [0.95767456 0.04232544]
 [0.00735609 0.99264391]
 [0.00179559 0.99820441]
 [0.00282054 0.99717946]
 [0.94693165 0.05306835]
 [0.05552791 0.94447209]
 [0.98784341 0.01215659]
 [0.00675125 0.99324875]
 [0.94502304 0.05497696]
 [0.50898879 0.49101121]
 [0.91758022 0.08241978]
 [0.98480203 0.01519797]
 [0.8214451  0.1785549 ]
 [0.82424239 0.17575761]
 [0.97483716 0.02516284]
 [0.95806368 0.04193632]
 [0.08070556 0.91929444]
 [0.98337064 0.01662936]
 [0.90882716 0.09117284]
 [0.26403182 0.73596818]
 [0.92731327 0.07268673]
 [0.03761114 0.96238886]
 [0.28582689 0.71417311]
 [0.0394042  0.9605958 ]
 [0.98150696 0.01849304]
 [0.97796464 0.02203536]
 [0.00564103 0.99435897]
 [0.0970953  0.9029047 ]
 [0.89504002 0.10495998]
 [0.93597942 0.06402058]
 [0.97990924 0.02009076]]

In [ ]:
#predict_proba
#The difference between predict and predict_proba is that predict will give you output like 0,1.
#Whereas predict_proba will give you the probability value of y being 0 or 1.
#In your case it says there is 23% probability of point being 0 and 76% probability of point being 1.
#Now where to use predict and predict_proba.
#Predict can be used normally to get prediction values.
#But suppose you are working on cancer diagnosis problem and you want to be very sure with your results. 
#So in that case you can use predict_proba which will give you class probability values and you can set some threshold like if predict_proba_value > .98 return class 1 else 0.
#So basically with the help of predit_proba we can set threshold as per our needs.

In [11]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8766666666666667

In [12]:
from sklearn.metrics import f1_score
print(f1_score(y_test,y_pred))

0.8683274021352313